[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Resource-Policy = "cross-origin"
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"
    Content-Security-Policy = """
      default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval';
      script-src 'self' https: 'unsafe-inline' 'unsafe-eval';
      style-src 'self' https: 'unsafe-inline';
      img-src 'self' https: data: blob:;
      font-src 'self' https: data:;
      connect-src 'self' https:;
      media-src 'self' https: data: blob:;
      frame-src 'self' https:;
      worker-src 'self' blob:;
    """
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"